name: Telegram Pull Request Open Notifications

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  notify-pr:
    uses: jobmetric/github-notify/.github/workflows/telegram-pull-request-open-notify.yml@master
    with:
      date_format: jalali
      timezone: Asia/Tehran
    secrets:
      bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}

